name: 'Get & Cache Dependencies'
description: 'Get the depencies(via npm) and cache them'
runs:
  using: 'composite'
  steps:
    - name: cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
    #   if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
